very_academy_ecommerce/Part-06 Managing Multiple Addresses - CRUD UUID/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = "account"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="account/login.html", form_class=UserLoginForm),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(next_page="/account/login/"), name="logout"),
    path("register/", views.account_register, name="register"),
    path("activate/<slug:uidb64>/<slug:token>)/", views.account_activate, name="activate"),
    # Reset password
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url="password_reset_email_confirm",
            email_template_name="account/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset/password_reset_confirm.html",
            success_url="password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/Mg/password_reset_complete/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_complete",
    ),
    # User dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("profile/edit/", views.edit_details, name="edit_details"),
    path("profile/delete_user/", views.delete_user, name="delete_user"),
    path(
        "profile/delete_confirm/",
        TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"),
        name="delete_confirmation",
    ),
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
]

very_academy_ecommerce/Part-06 Managing Multiple Addresses - CRUD UUID/basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

very_academy_ecommerce/Part-06 Managing Multiple Addresses - CRUD UUID/core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("account/", include("account.urls", namespace="account")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("__debug__/", include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

very_academy_ecommerce/Part-06 Managing Multiple Addresses - CRUD UUID/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='store_home'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

very_academy_ecommerce/Part-06 Managing Multiple Addresses - CRUD UUID/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <title>{% block title %}Store - Low Prices in Books & more{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
  </script>
  <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
  <link rel="stylesheet" href="{% block stylesheet %}{% endblock %}">
</head>

<body>
  <header class="pb-3">
    <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
      <div class="container-fluid px-md-4">
        <div class="d-flex w-100 navbar-collapse">
          <a class="navbar-brand d-flex-inline" href="/">
            <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="currentColor" class="bi bi-asterisk"
              viewBox="0 0 16 16">
              <path
                d="M8 0a1 1 0 0 1 1 1v5.268l4.562-2.634a1 1 0 1 1 1 1.732L10 8l4.562 2.634a1 1 0 1 1-1 1.732L9 9.732V15a1 1 0 1 1-2 0V9.732l-4.562 2.634a1 1 0 1 1-1-1.732L6 8 1.438 5.366a1 1 0 0 1 1-1.732L7 6.268V1a1 1 0 0 1 1-1z" />
            </svg>
          </a>
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle d-none d-md-block fw500" href="#" id="navbarDropdown" role="button"
                data-bs-toggle="dropdown" aria-expanded="false">
                All
                <i class="ps-1"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-chevron-down" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                      d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
                  </svg></i>
              </a>
              <ul class="dropdown-menu rounded-0 border-0" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url "store:store_home" %}">All</a></li>
                {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                  <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                </li>
                {% endfor %}
              </ul>
            </li>
          </ul>
          <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
            aria-label="Toggle navigation">
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-list"
                viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                  d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
              </svg>
            </div>
            <span class="fs15 fw500">Shop</span>
          </button>
          <div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent2">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle text-reset" href="#" id="navbarDropdown" role="button"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    <div class="small text-muted">Hello,
                      {% if user.is_authenticated %}
                        {{ request.user.name }}
                      {% else %}
                      Login
                      {% endif %}
                    </div>
                    <span class="fs15 fw500">Account &amp; Lists
                    </span>
                    </span>
                  </a>
                  <div class="dropdown-menu rounded-0" aria-labelledby="navbarDropdown">
                    <div class="card border-0">
                      <div class="card-body">
                        <h6 class="card-title">My Account</h6>
                        <ul class="list-group list-group-flush dropdown-account-link">
                          {% if user.is_authenticated %}
                          <a href="{% url "account:dashboard" %}" class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">Your Account</a>
                          <a href="#" class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">Orders</a>
                          <a href="{% url "account:logout" %}" class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">Logout</a>      
                          {% else %}
                          <a href="{% url "account:login" %}" class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">Login</a>
                          {% endif %}
                        </ul>
                      </div>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
          <a type="button" role="button" href="{% url "basket:basket_summary" %}"
            class="btn btn-outline-secondary border-0 basket-btn">
            {% with total_qty=basket|length %}
            <div id="basket-qty" class="basket-qty">
              {% if total_qty > 0 %}
              {{ total_qty }}
              {% else %}
              0
              {% endif %}
            </div>
            {% endwith %}
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-cart3"
                viewBox="0 0 16 16">
                <path
                  d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
              </svg>
            </div>
            <span class="fs15 fw500">Basket</span>
          </a>
        </div>
        <div class="d-md-none d-lg-none d-xl-none">
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li><a class="dropdown-item" href="{% url "store:store_home" %}">All</a></li>
              {% for c in categories %}
              <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
              </li>
              {% endfor %}
            </ul>
            <h6 class="card-title">My Account</h6>
              <ul class="list-group list-group-flush dropdown-account-link">
                {% if user.is_authenticated %}
                <a href="{% url "account:dashboard" %}" class="dropdown-item">Your Account</a>
                <a href="#" class="dropdown-item">Orders</a>
                <a href="{% url "account:logout" %}" class="dropdown-item">Logout</a>      
                {% else %}
                <a href="{% url "account:login" %}" class="dropdown-item">Login</a>
                {% endif %}
              </ul>
          </div>
        </div>
        <form class="d-flex w-100 d-md-none">
          <input class="form-control me-2" type="search" placeholder="Search products or FAQ" aria-label="Search">
          <button class="btn btn-outline-secondary" type="submit">Search</button>
        </form>
      </div>
    </nav>
  </header>

  <main class="pt-5">
    <div id="content">{% block content %} {% endblock %}</div>
  </main>

  <footer class="container py-5 footer">
    <hr>
    <div class="row pt-4">
      <div class="col-12 col-md">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-asterisk"
          viewBox="0 0 16 16">
          <path
            d="M8 0a1 1 0 0 1 1 1v5.268l4.562-2.634a1 1 0 1 1 1 1.732L10 8l4.562 2.634a1 1 0 1 1-1 1.732L9 9.732V15a1 1 0 1 1-2 0V9.732l-4.562 2.634a1 1 0 1 1-1-1.732L6 8 1.438 5.366a1 1 0 0 1 1-1.732L7 6.268V1a1 1 0 0 1 1-1z" />
        </svg>
        <small class="d-block mb-3 text-muted">&copy; 2017-2021</small>
      </div>
      <div class="col-6 col-md fs15">
        <h5>Features</h5>
        <ul class="list-unstyled">
          <li><a class="link-secondary text-decoration-none" href="#">Cool stuff</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Random feature</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Team feature</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Stuff for developers</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Another one</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Last time</a></li>
        </ul>
      </div>
      <div class="col-6 col-md fs15">
        <h5>Resources</h5>
        <ul class="list-unstyled">
          <li><a class="link-secondary text-decoration-none" href="#">Resource name</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Resource</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Another resource</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Final resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md fs15">
        <h5>Resources</h5>
        <ul class="list-unstyled">
          <li><a class="link-secondary text-decoration-none" href="#">Business</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Education</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Government</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Gaming</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled">
          <li><a class="link-secondary text-decoration-none" href="#">Team</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>
</body>

</html>